# Generated by Django 5.0 on 2024-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_products', '0003_remove_productimage_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
