# Generated by Django 5.0 on 2024-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_task_completed_task_assignee_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
    ]
